export const mockTableArray = {
  studentCount: 2000,
  students: [
    {
      id: 1117,
      first_name: 'Abagael',
      last_name: 'Sommer',
      email: 'asommer38@netvibes.com',
      phone: '6947516585',
      hours_studied: 188,
      primary_group: 'common',
    },
    {
      id: 131,
      first_name: 'Abdel',
      last_name: 'Henriquet',
      email: 'ahenriquet3m@360.cn',
      phone: '2538263043',
      hours_studied: 84,
      primary_group: 'important',
    },
    {
      id: 1194,
      first_name: 'Abdul',
      last_name: 'Nunns',
      email: 'anunns5d@sohu.com',
      phone: '2308974902',
      hours_studied: 14,
      primary_group: 'common',
    },
    {
      id: 1355,
      first_name: 'Abe',
      last_name: 'Lavis',
      email: 'alavis9u@skype.com',
      phone: '5483556671',
      hours_studied: 102,
      primary_group: 'close to lost',
    },
    {
      id: 1195,
      first_name: 'Abelard',
      last_name: 'Sabine',
      email: 'asabine5e@icq.com',
      phone: '5189276262',
      hours_studied: 258,
      primary_group: 'common',
    },
    {
      id: 1458,
      first_name: 'Abie',
      last_name: 'Goding',
      email: 'agodingcp@paypal.com',
      phone: '5561869539',
      hours_studied: 142,
      primary_group: 'common',
    },
    {
      id: 600,
      first_name: 'Adams',
      last_name: 'Crawley',
      email: 'acrawleygn@shinystat.com',
      phone: '7918677635',
      hours_studied: 137,
      primary_group: 'lost',
    },
    {
      id: 1080,
      first_name: 'Adara',
      last_name: 'Bleasdale',
      email: 'ableasdale27@themeforest.net',
      phone: '8909982898',
      hours_studied: 25,
      primary_group: 'important',
    },
    {
      id: 1078,
      first_name: 'Addy',
      last_name: 'Bastiman',
      email: 'abastiman25@zdnet.com',
      phone: '3892534820',
      hours_studied: 56,
      primary_group: 'lost',
    },
    {
      id: 746,
      first_name: 'Adele',
      last_name: 'Camamile',
      email: 'acamamilekp@biblegateway.com',
      phone: '5708041217',
      hours_studied: 27,
      primary_group: 'lost',
    },
  ],
};

export const singleResultMock = {
  studentCount: 1,
  students: [
    {
      id: 1117,
      first_name: 'Abagael',
      last_name: 'Sommer',
      email: 'asommer38@netvibes.com',
      phone: '6947516585',
      hours_studied: 188,
      primary_group: 'common',
    },
  ],
};

export const descResultMock = {
  studentCount: 2000,
  students: [
    {
      id: 1484,
      first_name: 'Zorah',
      last_name: 'Chimes',
      email: 'zchimesdf@wordpress.com',
      phone: '3524430729',
      hours_studied: 8,
      primary_group: 'lost',
    },
    {
      id: 1987,
      first_name: 'Zolly',
      last_name: 'Doyle',
      email: 'zdoylere@hp.com',
      phone: '6732101407',
      hours_studied: 201,
      primary_group: 'common',
    },
    {
      id: 560,
      first_name: 'Zitella',
      last_name: 'Aime',
      email: 'zaimefj@about.me',
      phone: '5058703537',
      hours_studied: 276,
      primary_group: 'common',
    },
    {
      id: 147,
      first_name: 'Zena',
      last_name: 'Newart',
      email: 'znewart42@telegraph.co.uk',
      phone: '3932360810',
      hours_studied: 131,
      primary_group: 'important',
    },
    {
      id: 1862,
      first_name: 'Zebulen',
      last_name: 'Lucock',
      email: 'zlucocknx@home.pl',
      phone: '8687309535',
      hours_studied: 31,
      primary_group: 'close to lost',
    },
    {
      id: 1369,
      first_name: 'Zebadiah',
      last_name: 'Dutt',
      email: 'zdutta8@cyberchimps.com',
      phone: '8044405065',
      hours_studied: 67,
      primary_group: 'common',
    },
    {
      id: 346,
      first_name: 'Zea',
      last_name: 'Shirland',
      email: 'zshirland9l@cdbaby.com',
      phone: '1722762170',
      hours_studied: 46,
      primary_group: 'Very important',
    },
    {
      id: 862,
      first_name: 'Zachery',
      last_name: 'Caunt',
      email: 'zcauntnx@xinhuanet.com',
      phone: '3084456111',
      hours_studied: 32,
      primary_group: 'important',
    },
    {
      id: 1696,
      first_name: 'Zacherie',
      last_name: 'Woodruffe',
      email: 'zwoodruffejb@wix.com',
      phone: '5692004506',
      hours_studied: 247,
      primary_group: 'Very important',
    },
    {
      id: 1892,
      first_name: 'Zachary',
      last_name: 'Bramhill',
      email: 'zbramhillor@wikimedia.org',
      phone: '6911083325',
      hours_studied: 240,
      primary_group: 'close to lost',
    },
  ],
};

export const page2ResultsMock = {
  studentCount: 2000,
  students: [
    {
      id: 612,
      first_name: 'Adele',
      last_name: 'Gervaise',
      email: 'agervaisegz@google.pl',
      phone: '6152081917',
      hours_studied: 132,
      primary_group: 'important',
    },
    {
      id: 170,
      first_name: 'Adelle',
      last_name: 'Ballantyne',
      email: 'aballantyne4p@adobe.com',
      phone: '2969341345',
      hours_studied: 133,
      primary_group: 'important',
    },
    {
      id: 414,
      first_name: 'Adi',
      last_name: 'Farish',
      email: 'afarishbh@hao123.com',
      phone: '1386792756',
      hours_studied: 173,
      primary_group: 'close to lost',
    },
    {
      id: 47,
      first_name: 'Adi',
      last_name: 'Elcomb',
      email: 'aelcomb1a@baidu.com',
      phone: '6371887501',
      hours_studied: 115,
      primary_group: 'close to lost',
    },
    {
      id: 200,
      first_name: 'Adolpho',
      last_name: 'Viall',
      email: 'aviall5j@dmoz.org',
      phone: '7431630459',
      hours_studied: 76,
      primary_group: 'common',
    },
    {
      id: 6,
      first_name: 'Adora',
      last_name: 'Burborough',
      email: 'aburborough5@cyberchimps.com',
      phone: '7654287845',
      hours_studied: 4,
      primary_group: 'common',
    },
    {
      id: 663,
      first_name: 'Adrian',
      last_name: 'Ferraron',
      email: 'aferraronie@geocities.com',
      phone: '5792105437',
      hours_studied: 121,
      primary_group: 'close to lost',
    },
    {
      id: 942,
      first_name: 'Adrianne',
      last_name: 'Ronan',
      email: 'aronanq5@ifeng.com',
      phone: '7791018179',
      hours_studied: 288,
      primary_group: 'lost',
    },
    {
      id: 142,
      first_name: 'Aeriela',
      last_name: 'Painter',
      email: 'apainter3x@usgs.gov',
      phone: '9023632664',
      hours_studied: 254,
      primary_group: 'lost',
    },
    {
      id: 256,
      first_name: 'Agatha',
      last_name: 'Garham',
      email: 'agarham73@japanpost.jp',
      phone: '3084106529',
      hours_studied: 61,
      primary_group: 'Very important',
    },
  ],
};

export const nonExistentMock = {
  studentCount: 0,
  students: [],
};
